#!/usr/bin/env ruby
require 'json'
require_relative 'helpers'
require_relative './memory'
require_relative './adjacent_memory'

#task 1
memory = Memory.new($stdout)
memory.find_point(ARGV)

#task 2
adjacent_memory = AdjacentMemory.new($stdout)
adjacent_memory.find_point(ARGV)
exit(0)